### ISSUE TITLE
Base rules

### ISSUE THREAD

**Issue by codecreative** [danielhusar/no-media-queries#2]
Hi, thanks for building this, very interesting. It seems as though the base rules are not applied, is that correct? So in the example if I passed a width of 400, I get nothing instead of blue. I've had a quick look through the code and tests and this is my understanding. Just wondering if I am doing something wrong or if that is the way it would work. Considering forking and exploring adding in the base rules. Anything in your experience that would stop that from being achievable or any advice?
Appreciate it,
Byron

**Comment by danielhusar** [comment]
Hey,

it will extract only css inside media queries that match the passed breakpoint.
